### ISSUE TITLE
Sometimes it will output one line more, and I found the solution.

### ISSUE THREAD

**Issue by zhaobey** [bcsanches/dbf2txt#1]
while(!clFile.eof())
    {
        char deleted;
        clFile.read(&deleted, 1);  
        if(deleted == 0x2A)
        {
            clFile.seekg(szRowSize, std::ios_base::cur);
            continue;
        }
        **if(clFile.fail())
        break;**
    ...

```
    out << std::endl;
}
```

add that comment.

**Comment by jlarapr** [comment]
while(!clFile.eof())
{
char deleted;
clFile.read(&deleted, 1);
if(deleted == 0x2A)
{
clFile.seekg(szRowSize, std::ios_base::cur);
continue;
}
if(clFile.fail())
break;

**if (deleted == 0x1A) //end-of-file
     break;**


...

    out << std::endl;
}

**Comment by bcsanches** [comment]
Can you provide a pull request?

**Comment by bcsanches** [comment]
Implemented the changes

**Comment by jlarapr** [comment]
Hello,

what do you need?

Cordialmente,

José O. Lara, MBA, MCP
Analista de Sistema

*************************Attention*************************
This electronic message, including any attachments, contains information that may be legally confidential and/or privileged. The information is intended solely for the individual or entity named above and access by anyone else is unauthorized. If you are not the intended recipient, any disclosure, copying, distribution, or use of the contents of this information is prohibited and may be unlawful. If you have received this electronic transmission in error, please reply immediately to the sender that you have received the message in error and delete it from your system.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by bcsanches** [comment]
nothing thanks, pushed some changes that I think fixed the issue. 

Thank you!

**Comment by jlarapr** [comment]
ok,

thanks

Cordialmente,

José O. Lara, MBA, MCP
Analista de Sistema

*************************Attention*************************
This electronic message, including any attachments, contains information that may be legally confidential and/or privileged. The information is intended solely for the individual or entity named above and access by anyone else is unauthorized. If you are not the intended recipient, any disclosure, copying, distribution, or use of the contents of this information is prohibited and may be unlawful. If you have received this electronic transmission in error, please reply immediately to the sender that you have received the message in error and delete it from your system.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by jlarapr** [comment]
Hello,
I use your code, I changed it a bit and I adapt it to what I am doing, dbf files to Sqlite.

void

DbfFile_c

::

DumpAllAndCreateSqlFile

(

const

char

*szDestFileName,

const

char

*szDestFileNameInsert,

std

::

string

primaryKeyField)

{//this method creates two .sql files, first file, create table, second file, insert data

std

::

ofstream

out(szDestFileName);

std

::

ofstream

outInsert(szDestFileNameInsert);

std

::

vector

<

char

>

vecBuffer;

vecBuffer.resize(szLargestFieldSize);

size_t

uTotalBytes

=

0

;

size_t

uNumRecords

=

0

;

bool

isStart

=

true

;

if

(tblName()

==

""

)

tblName(

"tmp"

);

string

sqlInsert

=

""

;

string

sqlInsertTmp

=

"INSERT

INTO

"

+

tblName()

+

"("

;

bool

starLoop

=

true

;

while

(

!

clFile.eof())

{

char

deleted;

clFile.read(

&

deleted,

1

);

sqlInsert

=

sqlInsertTmp;

if

(deleted

==

0x2A

)

{

clFile.seekg(

static_cast

<

int

>(szRowSize),

std

::

ios_base

::cur);

continue

;

}

if

(clFile.fail())

break

;

if

(deleted

==

0x1A

)

//end-of-file

break

;

//if

(deleted

==

0xf5)

{

//

cout

<<

"FoxPro

w.

memo

file"

<<

endl;

//}

if

(isStart)

{

string

sqlCreate

=

"CREATE

TABLE

"

+

tblName()

+

"("

;

string

sqlFilsType

=

"

TEXT"

;

out.write(sqlCreate.c_str(),

static_cast

<

int

>(sqlCreate.length()));

starLoop

=

true

;

for

(

size_t

i

=

0

;i

<

vecRecords.size();

++

i)

{

DbfRecord_s

&record

=

vecRecords

[

i

]

;

string

s

=

record.archName;

int

len

=

static_cast

<

int

>(s.length());

if

(

!

starLoop)

{

out.write(

","

,

1

);

sqlInsert

+=

","

;

}

starLoop

=

false

;

if

(strcmp(record

.

archName,primaryKeyField

.

c_str())

==

0

)

{

sqlFilsType

=

"

TEXT

NOT

NULL"

;

}

else

{

sqlFilsType

=

"

TEXT"

;

}

out.write(record.archName,len);

out.write(sqlFilsType.c_str(),

static_cast

<

int

>(sqlFilsType.length()));

sqlInsert

+=

trim(

s

);

sqlInsertTmp

=

sqlInsert;

//outInsert.write(record.archName,len);

}

out

.

write(

","

,

1

);

primaryKeyField.insert(

0

,

"PRIMARY

KEY("

);

primaryKeyField

+=

")"

;

out.write(primaryKeyField.c_str()

,

static_cast

<

int

>(primaryKeyField.length()));

out.write(

");"

,

2

);

out.flush();

out.close();

isStart

=

false

;

}

sqlInsert

+=

")

VALUES('"

;

outInsert.write(sqlInsert.c_str(),

static_cast

<

int

>(sqlInsert.length()));

sqlInsert

=

""

;

starLoop

=

true

;

for

(

size_t

i

=

0

;i

<

vecRecords.size();

++

i)

{

DbfRecord_s

&record

=

vecRecords

[

i

]

;

clFile.read(

&

vecBuffer

[

0

]

,

record.uLength);

if

(

!

starLoop)

outInsert.write(

",'"

,

2

);

outInsert.write(

&

vecBuffer

[

0

]

,

record.uLength);

outInsert.write(

"'"

,

1

);

uTotalBytes

+=

record.uLength;

starLoop

=

false

;

}

outInsert.write(

");"

,

2

);

++

uNumRecords;

++

uTotalBytes;

outInsert

<<

endl;

outInsert.flush();

}

std

::cout

<<

"Created

"

<<

uNumRecords

<<

",

records

"

<<

uTotalBytes

<<

"

bytes."

<<

std

::endl;

outInsert.close();

}

thanks,

Cordialmente,

José O. Lara, MBA, MCP
Analista de Sistema

*************************Attention*************************
This electronic message, including any attachments, contains information that may be legally confidential and/or privileged. The information is intended solely for the individual or entity named above and access by anyone else is unauthorized. If you are not the intended recipient, any disclosure, copying, distribution, or use of the contents of this information is prohibited and may be unlawful. If you have received this electronic transmission in error, please reply immediately to the sender that you have received the message in error and delete it from your system.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by bcsanches** [comment]
I would like to incorporate this as an option to users on the program. 

Can you please provide a pull request or a download? githut messaging created a real mess with the code

**Comment by jlarapr** [comment]
Hello,
I prepare a project and let you know

Cordialmente,

José O. Lara, MBA, MCP
Analista de Sistema

*************************Attention*************************
This electronic message, including any attachments, contains information that may be legally confidential and/or privileged. The information is intended solely for the individual or entity named above and access by anyone else is unauthorized. If you are not the intended recipient, any disclosure, copying, distribution, or use of the contents of this information is prohibited and may be unlawful. If you have received this electronic transmission in error, please reply immediately to the sender that you have received the message in error and delete it from your system.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by bcsanches** [comment]
great! Thank you!
Bruno Sanches
========================
http://www.pontov.com.br


Em ter, 30 de jul de 2019 às 09:24, Jose <notifications@github.com>
escreveu:

**Comment by jlarapr** [comment]
Hello,
verify this project :
https://github.com/jlarapr/jolOpenDBFTest
https://github.com/jlarapr/jolLibOpenDBF
https://github.com/jlarapr/jolSQLite3

let me know anything, it's the first time I share code on github

thanks,

Cordialmente,

José O. Lara, MBA, MCP
Analista de Sistema

*************************Attention*************************
This electronic message, including any attachments, contains information that may be legally confidential and/or privileged. The information is intended solely for the individual or entity named above and access by anyone else is unauthorized. If you are not the intended recipient, any disclosure, copying, distribution, or use of the contents of this information is prohibited and may be unlawful. If you have received this electronic transmission in error, please reply immediately to the sender that you have received the message in error and delete it from your system.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
